name: Ruby

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
jobs:
  ruby:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.51.1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run script
      env:
        TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
        TOGGL_WORKSPACE_ID: ${{ secrets.TOGGL_WORKSPACE_ID }}
        PIXELA_USERNAME: ${{ secrets.PIXELA_USERNAME }}
        PIXELA_TOKEN: ${{ secrets.PIXELA_TOKEN }}
      run: bundle exec ruby app.rb
